# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-13 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_set_username_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='instagram_id',
            field=models.BigIntegerField(),
        ),
    ]
