# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_location_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='is_photo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
